### ISSUE TITLE
Support for Counter-Strike 2

### ISSUE THREAD

**Issue by Arcanidus** [lociii/overwolf-homeassistant-webhook#7]
Hello sir, 

How can i help you or support you on the future possibility to extend support for Counter-Strike 2 ?

**Comment by lociii** [comment]
We just need to update the [config](https://github.com/lociii/overwolf-homeassistant-webhook/blob/main/src/consts.ts).

Some time ago I've built a [scraper](https://github.com/lociii/overwolf-homeassistant-webhook#scrape-game-features) for the Overwolf game event directory to update the config, however it's broken since they updated their website structure, see https://github.com/lociii/overwolf-homeassistant-webhook/issues/6

**Comment by lociii** [comment]
A test release with support for CS2 has been uploaded.
TBH I have no idea how test rollouts work with Overwolf. I will check later.

**Comment by lociii** [comment]
https://download.overwolf.com/install/Download?ExtensionId=iafnecpcfnepnifhkhbifmngngmpkbencicpfmmi&app_channel=Beta this is what Overwolf gives me

**Comment by lociii** [comment]
I've just fully released version 1.1.0 that supports CS2.
